name: GitHub Actions Reflector
description: Actions workflow for redirecting GitHub Actions event payloads to downstream applications.
author: 'Collin McNeese'
branding:
  icon: 'fast-forward'
  color: 'blue'
inputs:
  targetUrl:
    description: 'The event target URL.'
    required: true
  runner-label:
    description: 'The runner label to use.'
    required: false
    default: 'self-hosted'
runs:
  using: 'node16'
  main: 'index.js'
