name: GitHub Actions Forwarder
description: Actions workflow for forwarding GitHub Actions event payloads to downstream applications.
author: 'Collin McNeese'
branding:
  icon: 'fast-forward'
  color: 'blue'
inputs:
  target-url:
    description: 'The event target URL.'
    required: true
  webhook-secret:
    description: 'The secret to use for signing the event payload.'
    required: false
  allow-list-source:
    description: 'Location to an allow list of target URL entries.'
    required: false
runs:
  using: node24
  main: 'dist/index.js'
