---
  name: ci

  on:
    pull_request:
      branches:
      - main
      paths:
        - 'package*.json'
        - '**/*.js'
        - '**/*.ts'
        - '.github/workflows/ci.yml'

  jobs:
    validation:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [24]
      steps:
        - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install Dependencies
          run: npm install
        - name: npm test
          run: npm test
        - name: Verify dist is up to date
          run: |
            if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
              echo "Detected uncommitted changes after build.  See status below:"
              git diff
              exit 1
            fi
          id: diff
